# This is a basic workflow to help you get started with Actions

name: neobotix-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "rolling" branch
  push:
    branches: [ "rolling" ]
  pull_request:
    branches: [ "rolling" ]
  schedule: #trigger for every friday at 5:30 UTC
    - cron: '30 5 * * 5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.7.7
        with:
          use-ros2-testing: false
      - uses: ros-tooling/action-ros-ci@0.3.13
        with:
          target-ros2-distro: rolling
          package-name: neo_local_planner2
          skip-tests: true
          colcon-defaults: |
            {
              "build": {
                "symlink-install": true
              }
            }

  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    strategy:
      fail-fast: false
      matrix:
        linter: [cpplint, uncrustify]

    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.7.7
    - uses: ros-tooling/action-ros-lint@0.1.3
      with:
        linter: ${{ matrix.linter }}
        package-name: neo_local_planner2
